/**
 * F1Website
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Race { 
    id?: number;
    raceDate?: string;
    laps?: number | null;
    trackId?: number;
    isVisible?: boolean;
}

