/**
 * F1Website
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrackDto { 
    id?: number;
    name?: string | null;
    country?: string | null;
    length?: number;
}

